export const UPDATE_ACTIVE_USER = 'UPDATE_ACTIVE_USER';
export const ADD_APPROVAL_TO_QUEUE = 'ADD_APPROVAL_TO_QUEUE';

export const REMOVE_APPROVAL_FROM_QUEUE = 'REMOVE_APPROVAL_FROM_QUEUE';

export const ADD_POINTS_TO_USER = 'ADD_POINTS_TO_USER';
